### ISSUE TITLE
Order > AMOUNT DEPOSITING field: value reset after focus gets back

### ISSUE THREAD

**Issue by mgarciap** [gnosis/dx-react#330] opened 2018-08-14 12:00 UTC
When creating an order, the `AMOUNT DEPOSITING` from the `Token Pair ETH / RDN` modal gets reset.
Deployment: https://dutchx-rinkeby.d.exchange

### Steps:
1. Pick Token Pair > Selected to receive `RDN`
2. Click on `Specify amount to deposit`
3. Enter `1` in the `AMOUNT DEPOSITING` input field
4. Hit TAB to move to the next field
5. Hit Shift+TAB to go back to item 3. The content gets reset and is empty now.

**Comment by anxolin** [comment] 2018-08-21 11:34
Thanks for reporting Manuel, we'll take a look into it

**Comment by W3stside** [comment] 2018-09-06 09:31
@mgarciap thanks Manuel - this is actually intended behaviour right now. May change in the future. Closing for now.

**Closed as completed by W3stside** 2018-09-06 09:31 UTC
