### ISSUE TITLE
Transaction succeeds with maximum amount available

### ISSUE THREAD

**Issue by damiandragobetzky** [gnosis/dx-react#448] opened 2019-01-10 15:26 UTC
Describe the bug:
User is able to submit a transaction with maximum possible deposit value.

To reproduce:
1- Go to http://slow-trade.eth/
2- Click on Deposit and choose a Token.
3- Click on Specify amount to deposit. 
4- Write the largest possible amount.
5- Submit the transaction.
6- Observe. 

Expected result:
Metamask shows a red text warning the user of not having enough funds, and "Confirm" button is greyed out.

Actual result:
The transaction succeeds.

Device: PC
OS: Windows 10 -Google chrome v71.0.3578.98
Net: Rinkeby.

**Comment by W3stside** [comment] 2019-01-17 14:11
@damiandragobetzky can you send me a video of this? can't reproduce

**Comment by W3stside** [comment] 2019-01-28 18:22
cannot reproduce, closing for now!

**Closed as completed by W3stside** 2019-01-28 18:22 UTC
